### PR TITLE
fix: cease autoplay when maidr is deactivated (outside the plot)

### PR DESCRIPTION
**Pull request by krishnanand5**
# Pull Request

## Description
This Pull request aims to address a background issue where autoplay continues to execute even after maidr has been deactivated on the plot by a user click outside the plot area. Changes made in this pull request check for availability of `plotData` once maidr has been deactivated to handle exceptions thrown by `autoplay()` gracefully.

## Related Issues
This Pull request aims to solve #522 

## Changes Made
`Autoplay()` previously did not consider the state of `plot.plotData` when trying to access the plot components. Should the user click outside the interactive plot area, maidr would be deactivated which would result in destruction of `plot` object. Hence, `Autoplay()` would be running in the background and attempt to access the `plot` object components which were not present and therefore would emit exceptions incessantly.

With the Heatmap, addressing the `Autoplay()` on inactive maidr is not sufficient. The heatmap itself needs to be prevented from accessing points once autoplay has ended and additionally, its related audio functions need to be handled should the plot data be empty.

## Checklist

- [X] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [X] I have performed a self-review of my own code and ensured it follows the project's coding standards.
- [X] I have tested the changes locally following `ManualTestingProcess.md`, and all tests related to this pull request pass.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, if applicable.
- [ ] I have added appropriate unit tests, if applicable.

## Additional Notes
This PR addresses ghost autoplay issues with Histogram, Scatterplot and Heatmap.

### CODE REVIEW

**Comment by jooyoungseo** [comment]
@ellvix It looks good to me. Please share your insight. One naive question: Why do we have to apply this fix to each of the plot types? Could we refactor our code to modularize this?

**Comment by jooyoungseo** [comment]
@krishnanand5 Please go ahead with this solution and apply to the other plots. Will refactor later if needed later.

**Comment by krishnanand5** [comment]
Greetings Professor,

I have pushed some changes that help to address the ghost autoplay issue on Scatterplot and Heatmap. Heatmap in particular, required some additional changes which were a result of handling the case of empty plot data on the `Autoplay()` function. I felt those collateral issues could be handled through this PR instead of creating fresh issues. 

Standard barplots do not face this issue and hence no changes were required.

Regards,
Krishna Anandan Ganesan.

**Comment by jooyoungseo** [comment]
Thanks, @krishnanand5. Have you tested the boxplot and histogram as well?

**Review by jooyoungseo — APPROVED** [review]
LGTM! Merge once you are ready.

**Comment by krishnanand5** [comment]
Greetings Professor,

Histogram was addressed as part of the draft PR. As far as boxplot is concerned, I experienced issues with the in-repo example where the components were not getting highlighted as I was traversing through the plot. 

I did not see the exceptions being thrown like how it was for the other plots. Having said that, I would like to investigate boxplot a bit further and address any issues I unearth separately.

Regards, 
Krishna Anandan Ganesan.

**Comment by jooyoungseo** [comment]
@krishnanand5 sounds like a plan! Thanks for your detailed description 👍

**Pull request merged**
