### PR TITLE
docs(example): Added example heatmap using Python seaborn and matplotlib

### LINKED ISSUE #355: [DOCS] Create examples of heatmap from Matplotlib/Seaborn
# Feature Request

## Description
Create examples from Matplotlib for heat plots

## Motivation
Since the core library is tight-fitted for SVGs from ggplot2, we need to explore more with SVGs from other libraries like Matplotlib & Seaborn

## Proposed Solution
Create at least one sample for the following plots
 - heatmap

## Checklist

- [x] I have searched for similar feature requests and confirmed that this is a new request.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the motivation behind this feature request.
- [x] I have outlined a proposed solution or ideas for implementing this feature.
- [ ] I have provided any additional context or screenshots if applicable.

### PR DESCRIPTION
**Pull request by saaivenk**
# Pull Request

## Description

Created example heatmap using Python matplotlib

## Related Issues

Closes #355 

## Changes Made

Added example code, SVG plot, maidr JSON, and raw data JSON for a heatmap created using matplotlib.

## Checklist

- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code and ensured it follows the project's coding standards.
- [x] I have tested the changes locally following `ManualTestingProcess.md`, and all tests related to this pull request pass.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, if applicable.
- [ ] I have added appropriate unit tests, if applicable.

## Additional Notes

**NOTE**
This plot doesn't highlight properly, since the heatmap box width is of different size. The fix is ready, but hasn't been merged yet

### CODE REVIEW

**Review by jooyoungseo — APPROVED** [review]
LGTM!

**Comment by jooyoungseo** [comment]
@SaaiVenkat -- I tested this manually and found a bug. The Z (fill) label is displayed as an undefined.

image

**Comment by saaivenk** [comment]
@jooyoungseo 
- I checked with the [tutorial2_heatmap.html](https://github.com/uiuc-ischool-accessible-computing-lab/maidr/blob/main/user_study_pilot/tutorial2_heatmap.html) in [this commit](https://github.com/uiuc-ischool-accessible-computing-lab/maidr/commit/1dbf652d8c7d8e1215fc691ccbafd2b4d8b3fc32).
- The Z label displays `undefined`. Is this an expected behavior?
Screenshot 2024-01-22 at 10 06 35 AM

**Comment by jooyoungseo** [comment]
@SaaiVenkat -- No, that's not an expected behavior. I think that's a bug. Could you please address the issue via a separate issue and PR?

**Comment by saaivenk** [comment]
> @SaaiVenkat -- No, that's not an expected behavior. I think that's a bug. Could you please address the issue via a separate issue and PR?

Sure Professor @jooyoungseo , I have updated this PR to include the Z label and tested it manually as well. I will create a new issue to address the same bug in tutorial2_heatmap.html

**Review by jooyoungseo — APPROVED** [review]
LGTM!

**Pull request merged**
