### PR TITLE
docs(example): Added example line plot using Python seaborn and matplotlib

### LINKED ISSUE #353: [FEAT] Create examples of lineplot from Matplotlib/Seaborn
# Feature Request

## Description
Create examples from Matplotlib for line plots

## Motivation
Since the core library is tight-fitted for SVGs from ggplot2, we need to explore more with SVGs from other libraries like Matplotlib & Seaborn

## Proposed Solution
Create at least one sample for the following plots
 - line plot

## Checklist

- [x] I have searched for similar feature requests and confirmed that this is a new request.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the motivation behind this feature request.
- [x] I have outlined a proposed solution or ideas for implementing this feature.
- [ ] I have provided any additional context or screenshots if applicable.

### PR DESCRIPTION
**Pull request by saaivenk**
# Pull Request

## Description

Created example line plot

## Related Issues

Closes #353  

## Changes Made

Added example code, SVG plot, maidr JSON, and raw data JSON for a line plot created using matplotlib.

## Checklist

- [x] I have read the [Contributor Guidelines](../CONTRIBUTING.md).
- [x] I have performed a self-review of my own code and ensured it follows the project's coding standards.
- [] I have tested the changes locally following `ManualTestingProcess.md`, and all tests related to this pull request pass.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, if applicable.
- [ ] I have added appropriate unit tests, if applicable.

## Additional Notes

**NOTE**
This plot fails in the B, T, S modes because the fix for matplotlib lineplot hasn't been merged yet

### CODE REVIEW

**Comment by jooyoungseo** [comment]
@SaaiVenkat  Why did you include changes for barplot in this PR?

**Comment by saaivenk** [comment]
> @SaaiVenkat Why did you include changes for barplot in this PR?

I just renamed the file to keep things uniform. I'll update that in a different chore PR.

**Comment by saaivenk** [comment]
> @SaaiVenkat Why did you include changes for barplot in this PR?

@jooyoungseo I have updated the PR to include only line plot changes

**Comment by jooyoungseo** [comment]
@SaaiVenkat Thanks! Also please rename the title folowing what I have done for your prior PR.

**Comment by saaivenk** [comment]
> @SaaiVenkat Thanks! Also please rename the title folowing what I have done for your prior PR.

Done Professor

**Review by jooyoungseo — APPROVED** [review]
LGTM! Thanks, @SaaiVenkat ! Please feel free to merge.

**Comment by saaivenk** [comment]
> Please feel free to merge.

@jooyoungseo I don't have the access to merge

**Pull request merged**
